import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";
import Background from "@/components/Background";
import 'core-js/stable'; 

export const metadata: Metadata = {
  title: "Le'20 Representações",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (!Promise.withResolvers) {
    Promise.withResolvers = function <T>() {
      let resolve: (value: T | PromiseLike<T>) => void = () => {}; 
      let reject: (reason?: unknown) => void = () => {}; 

      const promise = new Promise<T>((res, rej) => {
        resolve = res; 
        reject = rej; 
      });

      return { promise, resolve, reject };
    };
  }

  return (
    <html lang="pt-br">
      <body>
        <Menu />
        <main>
          {children}
        </main>
        <Footer />
        <Background />
      </body>
    </html>
  );
}
