import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";
import Background from "@/components/Background";


export const metadata: Metadata = {
  title: "Le'20 Representações",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Menu />
        <main>
        {children}
        </main>
        <Footer />
        <Background />
      </body>
    </html>
  );
}
